### ISSUE TITLE
<ul> tag not visible.

### ISSUE THREAD

**Issue by BSiddharth** [battleoverflow/tryhackme-dark-theme#2]
Hi, thanks for the theme.

### Issue
In dark mode `ul` is not visible. Reason is color for it is being set white. I am not sure what is the intended behaviour.

![image](https://github.com/user-attachments/assets/da366827-a3e9-4335-9bc3-42a0e2d99116)

### Page Link:
https://tryhackme.com/r/room/metasploitintro

**Comment by battleoverflow** [comment]
I just pushed a commit that should fix this issue. Let me know if you see any other inconsistencies!
